#pragma once

#include "status.h"

#define GAMEBOY_TYPE_ADDRESS (0x146)
#define CART_TYPE_ADDRESS (0x147)

enum GAMEBOY_TYPES{
	GAMEBOY = 0x0,
	SUPER_GAMEBOY = 0x3,
};

static unsigned char* gameboy_types[0x4] = {
	[GAMEBOY] = "GAMEBOY",
	[SUPER_GAMEBOY] = "SUPER GAMEBOY",
};

enum CART_TYPES {
	ROM_ONLY = 0x0,
	ROM_MBC1 = 0x1,
	ROM_MBC1_RAM = 0x2,
	ROM_MBC1_RAM_BATT = 0x3,
	ROM_MBC2 = 0x5,
	ROM_MBC2_BATTERY = 0x6,
	ROM_RAM = 0x8,
	ROM_RAM_BATTERY = 0x9,
	ROM_MMM01 = 0xb,
	ROM_MMM01_SRAM = 0xc,
	ROM_MMM01_SRAM_BATT = 0xd,
	ROM_MBC3_TIMER_BATT = 0xf,
	ROM_MBC3_TIMER_RAM_BATT = 0x10,
	ROM_MBC3 = 0x11,
	ROM_MBC3_RAM = 0x12,
	ROM_MBC3_RAM_BATT = 0x13,
	ROM_MBC5 = 0x19,
	ROM_MBC5_RAM = 0x1a,
	ROM_MBC5_RAM_BATT = 0x1b,
	ROM_MBC5_RUMBLE = 0x1c,
	ROM_MBC5_RUMBLE_SRAM = 0x1d,
	ROM_MBC5_RUMBLE_SRAM_BATT = 0x1e,
	POCKET_CAMERA = 0x1f,
	BANDAI_TAMA5 = 0xfd,
	HUDSON_HuC_3 = 0xfe,
	HUDSON_HuC_1 = 0xff,
};

static unsigned char* cart_types[256] = {
	[ROM_ONLY] = "ROM_ONLY",
	[ROM_MBC1] = "ROM_MBC1",
	[ROM_MBC1_RAM] = "ROM_MBC1_RAM",
	[ROM_MBC1_RAM_BATT] = "ROM_MBC1_RAM_BATT",
	[ROM_MBC2] = "ROM_MBC2",
	[ROM_MBC2_BATTERY] = "ROM_MBC2_BATTERY",
	[ROM_RAM] = "ROM_RAM",
	[ROM_RAM_BATTERY] = "ROM_RAM_BATTERY",
	[ROM_MMM01] = "ROM_MMM01",
	[ROM_MMM01_SRAM] = "ROM_MMM01_SRAM",
	[ROM_MMM01_SRAM_BATT] = "ROM_MMM01_SRAM_BATT",
	[ROM_MBC3_TIMER_BATT] = "ROM_MBC3_TIMER_BATT",
	[ROM_MBC3_TIMER_RAM_BATT] = "ROM_MBC3_TIMER_RAM_BATT",
	[ROM_MBC3] = "ROM_MBC3",
	[ROM_MBC3_RAM] = "ROM_MBC3_RAM",
	[ROM_MBC3_RAM_BATT] = "ROM_MBC3_RAM_BATT",
	[ROM_MBC5] = "ROM_MBC5",
	[ROM_MBC5_RAM] = "ROM_MBC5_RAM",
	[ROM_MBC5_RAM_BATT] = "ROM_MBC5_RAM_BATT",
	[ROM_MBC5_RUMBLE] = "ROM_MBC5_RUMBLE",
	[ROM_MBC5_RUMBLE_SRAM] = "ROM_MBC5_RUMBLE_SRAM",
	[ROM_MBC5_RUMBLE_SRAM_BATT] = "ROM_MBC5_RUMBLE_SRAM_BATT",
	[POCKET_CAMERA] = "POCKET_CAMERA",
	[BANDAI_TAMA5] = "BANDAI_TAMA5",
	[HUDSON_HuC_3] = "HUDSON_HuC_3",
	[HUDSON_HuC_1] = "HUDSON_HuC_1"
};

status loadROM(char* gamefile);

status unloadROM();
